name: master

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.12
          3.11
          3.10
    - run: pip3 install tox
    - run: tox
